App:
  env: nvd1

  # repo details
  image:
    repository: 515842265945.dkr.ecr.us-east-1.amazonaws.com/push
  initImage:
    repository: 515842265945.dkr.ecr.us-east-1.amazonaws.com/push-init-py
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 0.5
      memory: 1Gi

# push configs
push:
  RABBIT_MQ_SERVER: http://rabbit.nvd1.ovp.kaltura.prod:5672
  RABBIT_MQ_SERVER_HOSTS: http://rabbit.nvd1.ovp.kaltura.prod:5672
  rabbitUrl: rabbit.nvd1.ovp.kaltura.prod